version: "3"
services:
  echonet:
    build:
      context: ./
      dockerfile: echonet.dockerfile
    command: python3 /home/pi/wisun-gateway/main.py
    volumes:
      - .:/home/pi/wisun-gateway/
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    ports:
      - "3610:3610/udp"